### GET ALL
GET http://localhost:8080/api/user
Accept: application/json

### GET BY ID
GET http://localhost:8080/api/user/<id>
Accept: application/json

### CREATE
POST http://localhost:8080/api/user
Content-Type: application/json

{
  
}

### UPDATE
PUT http://localhost:8080/api/user/<id>
Content-Type: application/json

{
  
}

### DELETE
DELETE http://localhost:8080/api/user/<id>
Accept: application/json