### GET ALL
GET http://localhost:8080/api/computer
Accept: application/json

### GET BY ID
GET http://localhost:8080/api/computer/1
Accept: application/json

### CREATE
POST http://localhost:8080/api/computer
Content-Type: application/json

{
  "model": "MacBook Pro22"
}

### UPDATE
PUT http://localhost:8080/api/computer/1
Content-Type: application/json

{
  "model": "ThinkPad X1"
}

### DELETE
DELETE http://localhost:8080/api/computer/1
Accept: application/json